# Mandar Sanjay Chaudhari
# 220968222
# Section B Batch B4
# Week 2
# Manual Multivariate Regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('multivariate.xlsx')
df

Subject     Y  X1  X2
0        1  -3.7   3   8
1        2   3.5   4   5
2        3   2.5   5   7
3        4  11.5   6   3
4        5   5.7   2   1

In [3]:
x1 = np.array(df['X1'])
x1

array([3, 4, 5, 6, 2], dtype=int64)

In [4]:
x2 = np.array(df['X2'])
x2

array([8, 5, 7, 3, 1], dtype=int64)

In [5]:
y = np.array(df['Y'])
y

array([-3.7,  3.5,  2.5, 11.5,  5.7])

In [6]:
x1x2 = x1 * x2

x1x1 = x1 * x1

x2x2 = x2 * x2

x1y = x1 * y

x2y = x2 * y

print('x1x2 = ', x1x2)
print('x1x1 = ', x1x1)
print('x2x2 = ', x2x2)
print('x1y = ', x1y)
print('x2y = ', x2y)

x1x2 =  [24 20 35 18  2]
x1x1 =  [ 9 16 25 36  4]
x2x2 =  [64 25 49  9  1]
x1y =  [-11.1  14.   12.5  69.   11.4]
x2y =  [-29.6  17.5  17.5  34.5   5.7]


In [7]:
sum_x12 = np.sum(x1x1) - ((np.sum(x1) * np.sum(x1)) / len(x1))

sum_x22 = np.sum(x2x2) - ((np.sum(x2) * np.sum(x2)) / len(x2))

sum_x1y = np.sum(x1y) - ((np.sum(x1) * np.sum(y)) / len(x1))

sum_x2y = np.sum(x2y) - ((np.sum(x2) * np.sum(y)) / len(x2))

sum_x1x2 = np.sum(x1x2) - ((np.sum(x1) * np.sum(x2)) / len(x2))

print('sum_x12 = ', sum_x12)
print('sum_x22 = ', sum_x22)
print('sum_x1y = ', sum_x1y)
print('sum_x2y = ', sum_x2y)
print('sum_x1x2 = ', sum_x1x2)

sum_x12 =  10.0
sum_x22 =  32.8
sum_x1y =  17.80000000000001
sum_x2y =  -47.99999999999999
sum_x1x2 =  3.0


In [8]:
b1 = (((sum_x22) * (sum_x1y)) - ((sum_x1x2) * (sum_x2y))) / (((sum_x12) * (sum_x22)) - ((sum_x1x2) * (sum_x1x2)))

b2 = (((sum_x12) * (sum_x2y)) - ((sum_x1x2) * (sum_x1y))) / (((sum_x12) * (sum_x22)) - ((sum_x1x2) * (sum_x1x2)))

a = np.mean(y) - (b1*(np.mean(x1))) - (b2*(np.mean(x2)))

print('b1 = ' , b1)
print('b2 = ' , b2)
print('a = ' , a)

b1 =  2.2816300940438885
b2 =  -1.6721003134796237
a =  2.7995611285266406


In [9]:
#Regression Equation is

y = a + (b1*x1) + (b2*x2)
y

array([-3.7323511 ,  3.56557994,  2.5030094 , 11.47304075,  5.690721  ])

In [10]:
#Prediction
x1 = 3
x2 = 2
y = a + (b1*x1) + (b2*x2)
y

6.300250783699058

# Using Random Integer

In [11]:
x1 = np.random.randint(1, high=10,size=10)
x1

array([1, 1, 2, 4, 6, 1, 9, 8, 1, 6])

In [12]:
x2=np.random.randint(1,high=10,size=10)
x2

array([2, 5, 8, 1, 1, 2, 8, 9, 1, 8])

In [13]:
y=np.random.randint(1,high=10,size=10)
y

array([4, 5, 4, 8, 5, 8, 6, 2, 9, 7])

In [14]:
x1x2 = x1 * x2

x1x1 = x1 * x1

x2x2 = x2 * x2

x1y = x1 * y

x2y = x2 * y

print('x1x2 = ', x1x2)
print('x1x1 = ', x1x1)
print('x2x2 = ', x2x2)
print('x1y = ', x1y)
print('x2y = ', x2y)

x1x2 =  [ 2  5 16  4  6  2 72 72  1 48]
x1x1 =  [ 1  1  4 16 36  1 81 64  1 36]
x2x2 =  [ 4 25 64  1  1  4 64 81  1 64]
x1y =  [ 4  5  8 32 30  8 54 16  9 42]
x2y =  [ 8 25 32  8  5 16 48 18  9 56]


In [15]:
sum_x12 = np.sum(x1x1) - ((np.sum(x1) * np.sum(x1)) / len(x1))

sum_x22 = np.sum(x2x2) - ((np.sum(x2) * np.sum(x2)) / len(x2))

sum_x1y = np.sum(x1y) - ((np.sum(x1) * np.sum(y)) / len(x1))

sum_x2y = np.sum(x2y) - ((np.sum(x2) * np.sum(y)) / len(x2))

sum_x1x2 = np.sum(x1x2) - ((np.sum(x1) * np.sum(x2)) / len(x2))

print('sum_x12 = ', sum_x12)
print('sum_x22 = ', sum_x22)
print('sum_x1y = ', sum_x1y)
print('sum_x2y = ', sum_x2y)
print('sum_x1x2 = ', sum_x1x2)

sum_x12 =  88.9
sum_x22 =  106.5
sum_x1y =  -18.19999999999999
sum_x2y =  -36.0
sum_x1x2 =  52.5


In [16]:
b1 = (((sum_x22) * (sum_x1y)) - ((sum_x1x2) * (sum_x2y))) / (((sum_x12) * (sum_x22)) - ((sum_x1x2) * (sum_x1x2)))

b2 = (((sum_x12) * (sum_x2y)) - ((sum_x1x2) * (sum_x1y))) / (((sum_x12) * (sum_x22)) - ((sum_x1x2) * (sum_x1x2)))

a = np.mean(y) - (b1*(np.mean(x1))) - (b2*(np.mean(x2)))

print('b1 = ' , b1)
print('b2 = ' , b2)
print('a = ' , a)

b1 =  -0.007196495619524229
b2 =  -0.3344806007509387
a =  7.333229036295369


In [17]:
#Regression Equation is

y_pred = a + (b1*x1) + (b2*x2)
y_pred

array([6.65707134, 5.65362954, 4.64299124, 6.96996245, 6.95556946,
       6.65707134, 4.59261577, 4.26533166, 6.99155194, 4.61420526])

In [18]:
#Prediction
x1 = 3
x2 = 2

y_pred = a + (b1*x1) + (b2*x2)
y_pred

6.642678347934918

# Using Random Float

In [19]:
x1 = np.round(np.random.uniform(1, 10, 10), 2)
x1

array([5.78, 2.02, 1.48, 8.76, 6.1 , 4.62, 8.5 , 5.33, 7.02, 1.64])

In [20]:
x2 = np.round(np.random.uniform(1, 10, 10), 2)
x2

array([2.2 , 8.01, 5.5 , 1.46, 4.5 , 1.36, 7.77, 7.58, 3.37, 3.35])

In [21]:
y = np.round(np.random.uniform(1, 10, 10), 2)
y

array([9.76, 7.8 , 7.96, 3.05, 3.46, 1.61, 5.74, 6.78, 2.52, 2.54])

In [22]:
x1x2 = x1 * x2

x1x1 = x1 * x1

x2x2 = x2 * x2

x1y = x1 * y

x2y = x2 * y

print('x1x2 = ', x1x2)
print('x1x1 = ', x1x1)
print('x2x2 = ', x2x2)
print('x1y = ', x1y)
print('x2y = ', x2y)

x1x2 =  [12.716  16.1802  8.14   12.7896 27.45    6.2832 66.045  40.4014 23.6574
  5.494 ]
x1x1 =  [33.4084  4.0804  2.1904 76.7376 37.21   21.3444 72.25   28.4089 49.2804
  2.6896]
x2x2 =  [ 4.84   64.1601 30.25    2.1316 20.25    1.8496 60.3729 57.4564 11.3569
 11.2225]
x1y =  [56.4128 15.756  11.7808 26.718  21.106   7.4382 48.79   36.1374 17.6904
  4.1656]
x2y =  [21.472  62.478  43.78    4.453  15.57    2.1896 44.5998 51.3924  8.4924
  8.509 ]


In [23]:
sum_x12 = np.sum(x1x1) - ((np.sum(x1) * np.sum(x1)) / len(x1))

sum_x22 = np.sum(x2x2) - ((np.sum(x2) * np.sum(x2)) / len(x2))

sum_x1y = np.sum(x1y) - ((np.sum(x1) * np.sum(y)) / len(x1))

sum_x2y = np.sum(x2y) - ((np.sum(x2) * np.sum(y)) / len(x2))

sum_x1x2 = np.sum(x1x2) - ((np.sum(x1) * np.sum(x2)) / len(x2))

print('sum_x12 = ', sum_x12)
print('sum_x22 = ', sum_x22)
print('sum_x1y = ', sum_x1y)
print('sum_x2y = ', sum_x2y)
print('sum_x1x2 = ', sum_x1x2)

sum_x12 =  64.94384999999994
sum_x22 =  60.488999999999976
sum_x1y =  -16.507299999999958
sum_x2y =  31.933999999999997
sum_x1x2 =  -11.980699999999985


In [24]:
b1 = (((sum_x22) * (sum_x1y)) - ((sum_x1x2) * (sum_x2y))) / (((sum_x12) * (sum_x22)) - ((sum_x1x2) * (sum_x1x2)))

b2 = (((sum_x12) * (sum_x2y)) - ((sum_x1x2) * (sum_x1y))) / (((sum_x12) * (sum_x22)) - ((sum_x1x2) * (sum_x1x2)))

a = np.mean(y) - (b1*(np.mean(x1))) - (b2*(np.mean(x2)))

print('b1 = ' , b1)
print('b2 = ' , b2)
print('a = ' , a)

b1 =  -0.1627325185754814
b2 =  0.49569922654867404
a =  3.720400645964822


In [25]:
#Regression Equation is

y_pred = a + (b1*x1) + (b2*x2)

s = str(a)+" + "+str(b1)+"*x1 "+"+ "+str(b2)+"*x2"
print("The regression equation is: y_pred = ",s)

The regression equation is: y_pred =  3.720400645964822 + -0.1627325185754814*x1 + 0.49569922654867404*x2


In [26]:
#Prediction
X1 = 3
X2 = 2

y_pred = a + (b1*X1) + (b2*X2)
y_pred

4.223601543335726