# Mandar Sanjay Chaudhari
# 220968222
# Section B Batch B4
# Week 8
# Ensemble Part 2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("breast_cancer.csv")

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
string =['Id', 'Clump_thickness', 'Uniformity_Cell_Size','Uniformity_Cell_Shape', 'Marginal_Adhesion','Single_Epithelial_Cell_Size', 'Bare_Nuclei', 'Bland_Chromatin','Normal_Nucleoli', 'Mitoses', 'Class']
j=0
for i in df:
    df.rename(columns={i: string[j]},inplace=True)
    j+=1
df

Id  Clump_thickness  Uniformity_Cell_Size  Uniformity_Cell_Shape  \
0    1002945                5                     4                      4   
1    1015425                3                     1                      1   
2    1016277                6                     8                      8   
3    1017023                4                     1                      1   
4    1017122                8                    10                     10   
..       ...              ...                   ...                    ...   
693   776715                3                     1                      1   
694   841769                2                     1                      1   
695   888820                5                    10                     10   
696   897471                4                     8                      6   
697   897471                4                     8                      8   

     Marginal_Adhesion  Single_Epithelial_Cell_Size Bare_Nuclei  \
0                    5                            7          10   
1                    1                            2           2   
2                    1                            3           4   
3                    3                            2           1   
4                    8                            7          10   
..                 ...                          ...         ...   
693                  1                            3           2   
694                  1                            2           1   
695                  3                            7           3   
696                  4                            3           4   
697                  5                            4           5   

     Bland_Chromatin  Normal_Nucleoli  Mitoses  Class  
0                  3                2        1      2  
1                  3                1        1      2  
2                  3                7        1      2  
3                  3                1        1      2  
4                  9                7        1      4  
..               ...              ...      ...    ...  
693                1                1        1      2  
694                1                1        1      2  
695                8               10        2      4  
696               10                6        1      4  
697               10                4        1      4  

[698 rows x 11 columns]

In [5]:
df = df.drop('Id', axis=1)

In [6]:
df['Bare_Nuclei'] =pd.to_numeric(df['Bare_Nuclei'], errors='coerce').convert_dtypes() 

In [7]:
df.isnull().sum()
df=df.dropna()

In [8]:
Y = df['Class']


X = df.drop(['Class'], axis=1)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
cols = x_train.columns
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

In [11]:
from sklearn.neighbors import KNeighborsClassifier

# MAX VOTING

In [12]:
from sklearn.ensemble import VotingClassifier
model1 = KNeighborsClassifier(n_neighbors=5)
model2 = DecisionTreeClassifier(random_state=1)
model = VotingClassifier(estimators=[('lr', model1), ('dt', model2)], voting='hard')
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.9734513274336283

In [13]:
y_pred_test= model.predict(x_test)
y_pred_train= model.predict(x_train)

In [14]:
from sklearn.metrics import accuracy_score
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Model accuracy score: 0.9735
Training-set accuracy score: 0.9912


In [15]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_test)

print(cm)

[[148   1]
 [  5  72]]


In [16]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           2       0.97      0.99      0.98       149
           4       0.99      0.94      0.96        77

    accuracy                           0.97       226
   macro avg       0.98      0.96      0.97       226
weighted avg       0.97      0.97      0.97       226



# AVERAGING

In [17]:
model1 = KNeighborsClassifier(n_neighbors=5)
model2 = DecisionTreeClassifier(random_state=1)

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)

pred1=model1.predict_proba(x_test)
pred2=model2.predict_proba(x_test)

finalpred=(pred1+pred2)/2

finalpred

array([[0.3, 0.7],
       [1. , 0. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [0. , 1. ],
       [0.4, 0.6],
       [1. , 0. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [0.5, 0.5],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [0.8, 0.2],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [0. , 1. ],
       [0.7, 0.3],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [1. , 0. ],
       [0.1, 0.9],
       [1. , 0. ],
       [1. , 0. ],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [0. ,

In [18]:
x_test.shape

(226, 9)

In [19]:
y_pred_test=[]
for i in finalpred:
    if(i[0]>=0.5):
        y_pred_test.append(2)
    elif(i[1]>0.5):
        y_pred_test.append(4)

In [20]:
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score: 0.9735


In [21]:
cm = confusion_matrix(y_test, y_pred_test)

print(cm)

[[147   2]
 [  4  73]]


In [22]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           2       0.97      0.99      0.98       149
           4       0.97      0.95      0.96        77

    accuracy                           0.97       226
   macro avg       0.97      0.97      0.97       226
weighted avg       0.97      0.97      0.97       226



# WEIGHTED AVERAGE

In [23]:
model1 = KNeighborsClassifier(n_neighbors=5)
model2 = DecisionTreeClassifier(random_state=1)

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)

pred1=model1.predict_proba(x_test)
pred2=model2.predict_proba(x_test)

finalpred=(pred1*0.4+pred2*0.6)

finalpred

array([[0.24, 0.76],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.32, 0.68],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.6 , 0.4 ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.84, 0.16],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.76, 0.24],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.08, 0.92],
       [1.  , 0.  ],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.  ,

In [24]:
y_pred_test=[]
for i in finalpred:
    if(i[0]>=0.5):
        y_pred_test.append(2)
    elif(i[1]>0.5):
        y_pred_test.append(4)

In [25]:
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score: 0.9690


In [26]:
cm = confusion_matrix(y_test, y_pred_test)

print(cm)

[[146   3]
 [  4  73]]


In [27]:
print(classification_report(y_test, y_pred_test))

              precision    recall  f1-score   support

           2       0.97      0.98      0.98       149
           4       0.96      0.95      0.95        77

    accuracy                           0.97       226
   macro avg       0.97      0.96      0.97       226
weighted avg       0.97      0.97      0.97       226

