# Mandar Sanjay Chaudhari
# 220968222
# Section B Batch B4
# Week 8
# Ensemble Part 2

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("Iris.csv")

In [3]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [4]:
df = df.drop('Id', axis=1)

In [5]:
df['Species']=df['Species'].astype(str)

In [6]:
Y = df[['Species']]
X = df.drop(['Species'], axis=1)

In [7]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=0)

In [8]:
from sklearn.preprocessing import StandardScaler
cols = x_train.columns
scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)

x_test = scaler.transform(x_test)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

# MAX VOTING

In [10]:
from sklearn.ensemble import VotingClassifier
model1 = KNeighborsClassifier(n_neighbors=5)
model2 = DecisionTreeClassifier(random_state=1)
model = VotingClassifier(estimators=[('lr', model1), ('dt', model2)], voting='hard')
model.fit(x_train,y_train)
model.score(x_test,y_test)

D:\Anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:97: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
D:\Anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


0.96

In [11]:
y_pred_test= model.predict(x_test)
y_pred_train= model.predict(x_train)

In [12]:
from sklearn.metrics import accuracy_score
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

Model accuracy score: 0.9600
Training-set accuracy score: 0.9900


In [13]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_test)

print(cm)

[[16  0  0]
 [ 0 18  1]
 [ 0  1 14]]


In [14]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       0.95      0.95      0.95        19
 Iris-virginica       0.93      0.93      0.93        15

       accuracy                           0.96        50
      macro avg       0.96      0.96      0.96        50
   weighted avg       0.96      0.96      0.96        50



# AVERAGING

In [15]:
model1 = KNeighborsClassifier(n_neighbors=5)
model2 = DecisionTreeClassifier(random_state=1)

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)

pred1=model1.predict_proba(x_test)
pred2=model2.predict_proba(x_test)

finalpred=(pred1+pred2)/2

finalpred

D:\Anaconda\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([[0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 1. , 0. ],
       [0. , 0.1, 0.9],
       [0. , 1. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 0.8, 0.2],
       [0. , 0.9, 0.1],
       [1. , 0. , 0. ],
       [0. , 0.8, 0.2],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 1. , 0. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.1, 0.9],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.2, 0.8],
       [0. , 0. , 1. ],
       [0. , 1. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0. , 1. ],
       [0. , 0.9, 0.1],
       [0. , 1. , 0. ],
       [0. , 0. , 1. ],
       [1. , 0. 

In [16]:
y_pred_test=[]
for i in finalpred:
    if(i[0]>0.5):
        y_pred_test.append('Iris-setosa')
    if(i[1]>0.5):
        y_pred_test.append('Iris-versicolor')
    if(i[2]>0.5):
        y_pred_test.append('Iris-virginica')

In [17]:
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score: 0.9800


In [18]:
cm = confusion_matrix(y_test, y_pred_test)

print(cm)

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]]


In [19]:
print(classification_report(y_test, y_pred_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.95      0.97        19
 Iris-virginica       0.94      1.00      0.97        15

       accuracy                           0.98        50
      macro avg       0.98      0.98      0.98        50
   weighted avg       0.98      0.98      0.98        50



# WEIGHTED AVERAGE

In [20]:
model1 = KNeighborsClassifier(n_neighbors=5)
model2 = DecisionTreeClassifier(random_state=1)

model1.fit(x_train,y_train)
model2.fit(x_train,y_train)

pred1=model1.predict_proba(x_test)
pred2=model2.predict_proba(x_test)

finalpred=(pred1*0.4+pred2*0.6)

finalpred

D:\Anaconda\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


array([[0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.92, 0.08],
       [0.  , 1.  , 0.  ],
       [0.  , 0.08, 0.92],
       [0.  , 1.  , 0.  ],
       [0.  , 0.92, 0.08],
       [0.  , 0.84, 0.16],
       [0.  , 0.92, 0.08],
       [1.  , 0.  , 0.  ],
       [0.  , 0.84, 0.16],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.08, 0.92],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.16, 0.84],
       [0.  , 0.  , 1.  ],
       [0.  , 1.  , 0.  ],
       [1.  , 0.  , 0.  ],
 

In [21]:
y_pred_test=[]
for i in finalpred:
    if(i[0]>0.5):
        y_pred_test.append('Iris-setosa')
    if(i[1]>0.5):
        y_pred_test.append('Iris-versicolor')
    if(i[2]>0.5):
        y_pred_test.append('Iris-virginica')

In [22]:
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score: 0.9800


In [23]:
cm = confusion_matrix(y_test, y_pred_test)

print(cm)

[[16  0  0]
 [ 0 18  1]
 [ 0  0 15]]


In [24]:
print(classification_report(y_test, y_pred_test))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        16
Iris-versicolor       1.00      0.95      0.97        19
 Iris-virginica       0.94      1.00      0.97        15

       accuracy                           0.98        50
      macro avg       0.98      0.98      0.98        50
   weighted avg       0.98      0.98      0.98        50

